### ISSUE TITLE
Only zero validation pass

### ISSUE THREAD

**Issue by mprandot** [jlobos/rut.js#14]
This lib is accepting only 0 in validate method, like 00.000.000-0

Can someone confirm this?

**Comment by wlopez-enkoding** [comment]
C'mon dude... seriously ?

**Comment by mprandot** [comment]
@enKoding, this lib has a method called validate(), rigth?
00.000.000-0 is a valid RUT? The method returning true with this value is correct?
And you still ask to me? seriously dude?

*in my code i prevent this comportament, but the lib has a bug.

**Comment by enKoding** [comment]
Pull requests : 0

**Comment by wlopez-enkoding** [comment]
> @enKoding, this lib has a method called validate(), rigth?
> 00.000.000-0 is a valid RUT? The method returning true with this value is correct?
> And you still ask to me? seriously dude?
> 
> *in my code i prevent this comportament, but the lib has a bug.

Yeah I got the idea, but I really think that it's a minor bug... You can send your pull request though

**Comment by wlopez-enkoding** [comment]
Actually, could you also fix the validation for 0000000000000000000000-0 ?

**Comment by jlobos** [comment]
No se me ocurre como arreglar esto 😢

**Comment by wlopez-enkoding** [comment]
Verifica el largo y valida que no sean solo 0s... el resto debería entrar en la validación común y silvestre....
