### ISSUE TITLE
ReDoS vulnerability

### ISSUE THREAD

**Issue by matiaslopezd** [jlobos/rut.js#26]
Hi! The regex patterns you use it for test RUT is vulnerable to ReDoS attack in Node.

![image](https://user-images.githubusercontent.com/23618492/181427600-64706e6c-8ea7-4edf-8368-1c6029e1e96a.png)

**Comment by cgustav** [comment]
Hola, alguna solución para esto?

Se están aceptando Pull Request para este repo?

**Comment by anniesystems** [comment]
> Hola, alguna solución para esto?
> 
> Se están aceptando Pull Request para este repo?

podría incluirse una validación condicional al principio para que admitan mas de 13 caracteres.
